creation_rules:
  # Rule for setup-01
  - path_regex: 01-setup/.*\.(ya?ml|key)$
    key_groups:
      - age:
          - age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt # Dmytro Malovanyi
