apiVersion: ENC[AES256_GCM,data:D9el1Dz6TCU=,iv:u+BlG/L1jtSSllcSky5XmMmRr1SqRWqZKKFbzUUOsaE=,tag:ItXBMY7Y0yLmQf8ozYbKBw==,type:str]
kind: ENC[AES256_GCM,data:ifZsGLBNG/qbZ71c+EvLuQtl,iv:Ye2czxqzTchHN4T4mb0pAIYuFx12lNs/jFL7aw9Ya5o=,tag:kzX3BtHMk3QkohdCQtBfXQ==,type:str]
name: ENC[AES256_GCM,data:qynxYdrHFQ==,iv:JAvYdfApEYg6xg/1QiuPSSK4vc4Clh+UCjA6pm3z4ck=,tag:iTLgg5auARnamH5wIYxClw==,type:str]
username: ENC[AES256_GCM,data:9Ayby6/XfPaYW5w=,iv:3p/SJEjMyB2m7HupaPAT+4K6LHtozD5qFGDAdCbkbzI=,tag:o1nNeT+9meC5qqADJiXLWg==,type:str]
password: ENC[AES256_GCM,data:i5xfkn1EY/euXtS2tV5/93x0p2kdDWOXkfZv0kdmc5SBLlYUZlHQrA==,iv:58fGI6ewT7PLscifx/KhSVCscwfA7OsT86h8svBcu3U=,tag:N/VwCZz7KJpTVWIjnTKRvg==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0KysralVNR0lLeFVkREVi
            K3lUR0hMTTNlQ0RIM2RSWWhteUx6bEFFSnlrCmVXenFmTFBGaVQwVXlFMkRDZVQ2
            U1ZpMENXMzhHZGNkZy9POW9jcnpSRWcKLS0tIG9NUkJ0MlV5WVFBVEZDU0NZSmRJ
            dFlZb0psYjhHU2ZTSkRBTVluTTZGNTAKafag8YQSOO0+YKLtNlRxklESg8HRnZY9
            l1nIFlyHjg1fONNmVXp33fnKDvI0jI0dPNs37QNZYVldviMfsLm4QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T19:44:53Z"
    mac: ENC[AES256_GCM,data:Og9RHxenGgT20vLbYPpIIV8MdJqah3800uLiphM6+fUHp7WP+RjIVfU7JD5zauhiDcPxBPDXOX2Q/hsd1pSL6z/h0qpkDBeEDUElUNJeX909zb2fSPWeiie3dR/8xN+IhsvD8tA7GADlQMOgjuu85zvPsxwa3aeKOtHJq7jYOqk=,iv:cK8uPRsh7xQzyAjXlgXNoPtaYf1vF+XEh+sTilC+to8=,tag:pyTQLHrYRUI3IcRzAEcu+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
