apiVersion: ENC[AES256_GCM,data:JK6pdQikWxo=,iv:MqRlpFa4K05pNVIVzkbb/FM+XO6woGtAzj/BmpUXhDk=,tag:JG4CWnBj7EtcI4u6S39HIg==,type:str]
kind: ENC[AES256_GCM,data:pQ5dalLKrChT6Mbs/UdgIY+w,iv:09JzuH+DjJR7wz1djvCmty+1BD3AsZN91L86xNRfozA=,tag:mzFq5NPOqCbltqV25qb1RA==,type:str]
name: ENC[AES256_GCM,data:SFo7epde3w==,iv:9IKXNkrsFKR4on3VfA8v3u+WZXnip/H5EMnP8hiI7vI=,tag:Jyz86h3ScqMQp2pxJK0RxA==,type:str]
username: ENC[AES256_GCM,data:nIMbBbQ2c0KunAI=,iv:WpVPFZgyoXZFMl1gZrnFSQDKeypCS76U2Xx1AObhEdE=,tag:hquN/SZmXLTlBsM7ygZeOQ==,type:str]
password: ENC[AES256_GCM,data:LlZNl0DhPDc4MxFnBFasUogyllefW1ra3DgXz1+mUE4q2cuPds6sDw==,iv:wqFvE0uONEekc3MvSmwr3oLd0wuz0uV/62gROl48rWA=,tag:gFKwXG6fCrw/1HZIbFpF8Q==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSEd5aWt0Zm93TmxSVHFX
            Um9LbGwvTURCaGpUMHlxTXdVU2o4YkdmQ0Q0Cjh5T0w4cUJ5c2IxUHMzVTkwb0pQ
            OFEvV1AycUYzc3RyZnVXNEZnTU5MWncKLS0tIHE4OUtnZVZZemJrV3Z4RDJkMm1M
            WlFtU3RpeDNoNUUyVmd6ZUd3aDZFcXMKroUlTSl/F/B76twC6XiIXrSCEAm1Mo91
            8yD2ttDzMimKjK1sHQ7Q6RK5aceLv4jXXM5pYoPpHaH1teOIyuxJxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T14:09:13Z"
    mac: ENC[AES256_GCM,data:6T3bCwK01XxtTV/Vnizw2yOwr4j3C8u8LmrnNA1kQYr2PmpWFREuDlXlJ3n6bFKcqd3RYnSRULEIiGT+ig+c5AIu42DfJ50SMsfbrq+pTcZO8bDvvg/OlaBk112EI9xvNiZJk6a/avHmAIlOOsr9a0/Ybh6N/tN4CcBRTcbFBpk=,iv:QY4S7NDomodVusDuVVS64XibUTlTlw3UP5LwhjUL4yw=,tag:ob2vkZfnlfJP+zx6Qop5Ng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
