apiVersion: ENC[AES256_GCM,data:5QniwjfrtFw=,iv:p8MdzHC772df67J+2NIQYLp+fa5SmvcDh4427l/H+0E=,tag:BO/8R9ReE5+xaCHWVOD1xg==,type:str]
kind: ENC[AES256_GCM,data:fKXWYk6tE6Mf03VHGzftNmT9,iv:qaVOnJQI7TSAgqdIW4XHa/7kqOCM0XOaOlc6HwoLw4A=,tag:Q+xdAKFajPVxBvGHR2mXog==,type:str]
name: ENC[AES256_GCM,data:JFFdI0Lwkg==,iv:wjeTBOp0nb5pkGLFbVhbsJZRRvDSG9IAZSA9a8TiDqQ=,tag:3d3wIXK/VbYLoZN3z73TOQ==,type:str]
username: ENC[AES256_GCM,data:Z1s6F4FFJW7ZGZc=,iv:y9z8/yy+F3D+2WX/fp3rNf5eX2OgOEx86fq6K2J8Ehc=,tag:hpflYRuLCb/Nrxqc81kIWA==,type:str]
password: ENC[AES256_GCM,data:+bi0rN1B56BJj3DTHtXz5EtRgcsrtjH0W+VXVuInazuDDsiEr/+fkw==,iv:8rCAQendy9rSABmxEG79FFwxNJyGT0tHicIPzT068qI=,tag:AiYbDcEvZoj2ZVpFRtXKvw==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOFhkbENSZHNVVGRtemtN
            cFZCekJ4UGIwZWsxak42TjJoaU1QR2NHMndrClcrNy9ySEV5b2VvNG1qNUErRXZE
            eUE0MU9wTUZINEV5ODBDSEp1U0tnbncKLS0tIGFtMDNlOWViNGg2L2JQNE83eERn
            M0ZwNFJVODRxY3dkdk1keDk5amxvRDgKEsstZTwDlJMnFj1WhkC4IUVpwLwoo1AK
            VV6nrl1bgtlshHzp1q3VsALCHE2AeEGcrgjvstXPmb2q5sz5biC4IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T18:11:19Z"
    mac: ENC[AES256_GCM,data:hvwQYnK3McYji45evRgGMJuwHAlI6NrvgXYGgP+WCre2CVVx2C55rHubZ37z/p6uXQdaGjWOfOEwCAIs2p/ehRxl/kCoanVSskCfAXoFhfoGUNxy5pjyVxopywavfRyLioBoKxaCxonUTJwGq5O7n/o0VfSlBuQsKFxp/hoAd8Y=,iv:LnZmVmV32bGcN3pNRe8yugU53b2m+Bqo1/OG3x9WVD0=,tag:MVObEZeQX8nViVR4jQFnyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
