apiVersion: ENC[AES256_GCM,data:MYyrBEh66Gc=,iv:clWGSHfwdL0S8nNSSKZPnKJCsJj7D7R19WV+jIJ2tIo=,tag:1+cmyLTghFDXY8KXE3a+Ww==,type:str]
kind: ENC[AES256_GCM,data:/Ojh/2KT/c3egJbiEba8+n/GwVHe3w==,iv:AChZ5KkbCtN2i7XbnLI6PQ8mexF5bnGLAuhXLXWSxa4=,tag:slRNjqN0r82oo81bGiTUGg==,type:str]
name: ENC[AES256_GCM,data:b3xtJGOZ/VSp,iv:ys41EaY/5psYTvfS/4uge9x4WynNO7KX4bD9aqbZhL8=,tag:fUQD549Ceqy2zyZfFfafsQ==,type:str]
environment:
    - ENC[AES256_GCM,data:tG6qeATrgR3Qne94qtz7OfwRVVzhUxkOhQ1mSq8igdgMV8lhM5TOlMcyjRe+mSCGFWvnD2locr3JV3iNI+1EZXitHwuUbie27g==,iv:fMStBOXFNmD4ejOhBVgacsthofBHvMbrTsPVJ5doN/g=,tag:YFOgPKRNItGg4zh50wrg2Q==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TEwwTnVpYUhVcnA0ME9w
            Q3hjSVJCQ3ZIbXZGNWZqL29ONElBN2dTc1NnClhzb2lEV0RsMEc5R2l4Mk10SlN4
            bHFzK05yTExDMjBQOGdaQnp6M2IwODQKLS0tIGRFT2ZlTXduenJGejY4UWFoRFUy
            M0JLUTNzUk96R0JoZmtPZjVtMDhTRWMKLI/h4FKC4tkjuPGFNvt9uMPTJl64O07q
            dmC4hw0jqP2hsXCVLITEB/sVaNsUAsNG6YZCj8gjM8mfR6xQr/m0gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T12:55:12Z"
    mac: ENC[AES256_GCM,data:5GlF+xFnc8f0A5XmMmsEU34dxmpte9CVYzFI17dHb32Dnd5/c0AltrFcoFx1BxW3ef+A/HOoL5lpAcXkBZWk2X7I9T1FmFkqHc4JAC8OOAG9KtdiHn4TWoif4TUtFUw2QXYoJljC4duYFXErhTAzZeeTVX+sHIdDdIcSj5LrT04=,iv:hd5fby7TYw7AiAei8uDPtE8U1wE4LSJn9TUmsixDct0=,tag:xlowNUoVpL6GVppi7Cdq/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
