apiVersion: ENC[AES256_GCM,data:9kdrdEmuCdE=,iv:n9tNsOsKVO/k4r90tVsTdhCx0kq9M+sQsnQwcGamxz0=,tag:GeEIEG0PA79omDVIXS42IA==,type:str]
kind: ENC[AES256_GCM,data:sTo3op7SkgDd9PMlrohYJK/UXS1UIg==,iv:q0AVujsb538JWxAS+ioeEgCxQWgrxKefQyHHKv5DL0Q=,tag:ziTfshtMzbaUd1eCUHVjMQ==,type:str]
name: ENC[AES256_GCM,data:wWTgsBSEpGXw,iv:kp1I8Kh0G/oq+vkK26RjuoNAA1oy9UhDL5hlWpOUYTs=,tag:phzWhKGHPh6aEORr6tRfEw==,type:str]
environment:
    - ENC[AES256_GCM,data:eVxPQlkdlUSzb0K47uuDESZ9zPusEpr5Hb2YWRxK/npvi39zBW9u1uF/3ElpKLe4p135L1AB33XjkeMrNNz8C1y3eJcAH6TyDA==,iv:YZx+xv4gP86DcVBwx9jBz5UZOGZRuS+h42YL2UgPhFI=,tag:/Vg/0APRRgpu0lptSCzvSw==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNGZsZkZmeHMzMzNNT2Rm
            dEhDMjdFaS8yZmh3REpRQVNtbmFxQk9oTTNJCm8weFJZUWVhZkRydlNXQ1ZOYXJR
            NVB2cE1ENDgwL1hHVXRkRVozcnErRXMKLS0tIDQyYytVZ3BUUlRjYWhHRUJsYmdI
            aFAwOTlxNFRWVFd4dk03OXJsdkpEYncKBNbONhdHBokS3gMnFsQ+YJljY5c8eQTA
            s3IJYTRvEgBWqeOBXIlc9xJot4UmLjYblkkIwrrcH0JVsLx8LvLq4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T18:11:21Z"
    mac: ENC[AES256_GCM,data:PBvE9dtq9QEkviitidD2U2sijySCP3c4EQEBdlRwzEg9jLbukLLnza3dQxOVCUj3gvy6eSfHYhrnCeHM+b6zn3lmmRCHGbnUNNJ0Dsj29X4eWnhxNJrF+j7dw4Z7/6leZ9AUzM6vK+xnjd3SsG4gxnEvpmAiJzZD+WKYJydap/0=,iv:uWMnHMLGxrK7UlbTYyXqlcnbPFhTMEkGYvih2ArUFIo=,tag:Fj8oUQvugMrE7nKqWZK7hw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
