apiVersion: ENC[AES256_GCM,data:kgUbteRpVlw=,iv:JD7bdXlFSsi+V2HOl5tI9e4kKijh772y5pj5qCSAwZM=,tag:n5qDpLACqpptMEx7OELCKw==,type:str]
kind: ENC[AES256_GCM,data:NvYMd9pqDA/5Pr7Fkr2lfjz6NGDqlw==,iv:UKQZ+NX89uUD1RXaecFQ8XN/HsMebjEQzGk4hrJ8ycA=,tag:fwnQAwgDLYXqCGlCUXdoeg==,type:str]
name: ENC[AES256_GCM,data:ZAWjpAzX7kp3,iv:XKWxrCnsJXn0liaK2LA1Q2VKtXQclhh20sgknAgi8Xw=,tag:0RYvPQZdyy04V1lRqC+4/w==,type:str]
environment:
    - ENC[AES256_GCM,data:EoMe94Dsq/RgN4I2S/jMFZ6B65VWcU2Our+hc4LvRNdE0q1cu7BYROtQDahpB0ZbdzEX6HwuAlPQ4M37RH8O81Rp6tcN3iPV0g==,iv:J3nG0F11hdgTQD6gsr4xlECelBZHyq+eyiEAahC2Ucw=,tag:ngXMai7EoANvGjDWkgm82A==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlemMya01PZHNoMktjZkxa
            SytxNE5URVRwT0RtVnpJdFpMZVBzaGtCd3hFCjhVV3pnQ3RtOSs4aWpncGlCcmY5
            ZUVCdG90NFkzaUQ5blVTblE2OU9oZEkKLS0tIHRXTjl3ZFQzaXZza2FpU0E2bmUv
            SC9KSWttcHAyVitORkxrTmx0Y1lIeU0KQq2sXcwLy4twRdEyeDwivFF9SbpSlnIx
            4d4iLVsz5FzkhSZPMDzaYU618IlWboJB8vGqUn8UO4wFsRkZi/coBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T12:54:30Z"
    mac: ENC[AES256_GCM,data:23My5gQvN5CxCg9YSUhot4lqenFfqXvZFnicCr1THqJz2mJu0AgmCUTjukMbBTBD3KWHEJlIziO91zkTzvoRVbYJvi5IzzZgbyVwQJKDeBBoDOaQle3s69f5bMVXMExY2ztJQjvUi4Y0iKA9bbfc6eJDkNu5fztGI1pJ2Z/Vdmk=,iv:zUo8u4KJoWlUR2I2CN2dnJRncPSlVl75PmslKOxIDoU=,tag:S0HjP4bhUEkmKqpRs7E/Tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
