tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
  - key: node.kubernetes.io/location
    operator: Equal
    value: cloud
    effect: NoSchedule
  - key: node.cloudprovider.kubernetes.io/uninitialized
    operator: Equal
    value: "true"
    effect: NoSchedule
