kube-vim:
  vim:
    image:
      pullPolicy: Always
    nodeSelector:
      node.kubernetes.io/location: cloud
    tolerations:
    - key: node.kubernetes.io/location
      operator: Equal
      value: cloud
      effect: NoSchedule

    service:
      type: LoadBalancer
      loadBalancerClass: tailscale
      annotations:
        tailscale.com/proxy-class: default-proxy-class
        tailscale.com/hostname: setup02-kube-vim-grpc
    
    config:
      image:
        storageClass: local 
      compute:
        tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: edge
          effect: NoSchedule

  gateway:
    nodeSelector:
      node.kubernetes.io/location: cloud
    tolerations:
    - key: node.kubernetes.io/location
      operator: Equal
      value: cloud
      effect: NoSchedule

    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/proxy-class: default-proxy-class
      hosts:
      - host: setup02-kube-vim.tailac05db.ts.net
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - setup02-kube-vim.tailac05db.ts.net
