minio:
    auth:
        rootPassword: ENC[AES256_GCM,data:C7kd39cAyMg=,iv:hymKKfaABjkIYhFRjx0MKMMBc55PTgD6r7vHTvBCrWc=,tag:bRHmqSWmXDWq2RSp9viqQw==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT25kSHZ4L1BXY0kycFV6
            VkxVejM5N1dFOXFycDNEbi83Zmt0Y2RKb0hZCkY2UWk3YTJlZmJYNFdMUldFTWxE
            ZHJsVHM5TXRzdUJ4NTBJSmVndFZNaFkKLS0tIGFwVkl0UGVXUlNsVlBQVTJxU0JH
            cWFpNTZ3V2FpYlhFWWhMZGVBVklteWsK2Qs7XGFmvi2EZTl1rJHZrbheVw9MPP5m
            dcz0u4rBw752TlIX3KRarjICCIfKVHcz3h+DkSjcTQxggtquwOcKuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T16:06:56Z"
    mac: ENC[AES256_GCM,data:WA2o1kviHKM8GxSNYy90r5iV/KekZrt1h3Lxq+5YILHXegpHyJYf2FKUBQoNW8KJte+N2s6HpFKu9BEuPHw3nluUl2IuV9Qig9XdJoulXVJRdUjk1S33ySsDCA0LTu9K6eC2CMberQYnyQZXoEIzaBIul+q3gIe0lmtTshy7O0c=,iv:DW5mq1JCJCIZUTT+Cm9F1pepOpMMIcmuBUR6S7rk4kI=,tag:D+0QLr68eFVJCT0sgzprpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
