minio:
    auth:
        rootPassword: ENC[AES256_GCM,data:0G09YTWRGMQ=,iv:/1gXNaLuq/HlGiBXd9rzDgWSgua7MWyFcl0PPO6h0cE=,tag:KiVX5XaqpYINWrqyhrRJXQ==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNDBKT25yZ25iNlNsTSta
            MDZIV3IveE92TE1LK1hXeWRneXppa0FzZ0RnCnJzVDhLZlE0c0pCVVdGVVBqM2Ev
            WWJ6a0IyaGdZUy9lY2JMN3pFZHM2YlUKLS0tIGlwQXpkRnVFSmpsdGpIWmd6aWZU
            YnkwWUJUZzlDU0xNUWd2OVdBTit6cVUKV3GdrX1+pj+EVL4qsrFIj/7KE0UmjmHQ
            6od1B8pmmmaiAVdIMGla8JAiI8rwaSpVFyHFWarruLjtu0WJVQTCEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T18:11:10Z"
    mac: ENC[AES256_GCM,data:OjVpQixl7UC0iipXkNpno1TUtbncNAGsuTyScUA7EFxoEJCI5Z5UypZdJmz66hlNL+KOYqiYfmQgNPlSaiN3Df8f6MU3xEEsoSHHo1G0Wiq6GrzkVbnvYmBWmbbzuoMjAc9ttPY4i+fds0lCsJU2JG+DxF8ngADihUor2Fefsjo=,iv:XOaGrRf2Xu0O6oPHbpAXHZj8miXRWHBIyCzVzmkS+JM=,tag:XpCjP/P8/PMpBKq9S+xGjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
