apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-pf1-switchdev
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/mlx_vf_pf1
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "sriov-pf1-switchdev",
      "type": "sriov",
      "ipam": {}
    }
