apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: mlx-pf1
  namespace: sriov-network-operator
spec:
  nodeSelector:
    node.kubernetes.io/location: edge
  resourceName: mlx_vf_pf1
  numVfs: 2
  nicSelector:
    pfNames:
      - ens9f1np1
  deviceType: netdevice
  eSwitchMode: switchdev
