---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb
spec:
  addresses:
  - 10.0.10.210-10.0.10.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2add
  namespace: metallb
spec:
  ipAddressPools:
  - ip-pool
