apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-vlan100
  namespace: sriov-network-operator
spec:
  resourceName: mlx_vf_pf0
  networkNamespace: default
  vlan: 100
  ipam: |
    {
      "type": "static",
      "addresses": [{"address": "192.168.192.2/24"}],
      "routes": [{"dst": "192.168.192.0/24"}]
    }
