apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-vlan200
  namespace: sriov-network-operator
spec:
  resourceName: mlx_vf_pf1
  networkNamespace: default
  vlan: 200
  ipam: |
    {
      "type": "static",
      "addresses": [{"address": "192.168.181.2/24"}],
      "routes": [{"dst": "192.168.181.0/24"}]
    }
