operator:
  nodeSelector:
    node.kubernetes.io/location: cloud
  tolerations:
    - key: node.kubernetes.io/location
      operator: Equal
      value: cloud
      effect: NoSchedule
  hostEtcPath: "/var/etc"
  hostUdevPath: "/var/etc/udev"

images:
  operator: ghcr.io/kube-nfv/sriov-network-operator:56ff3adfe5e5a1294bb32da6fc31a3a2663e4049

sriovOperatorConfig:
  deploy: true
  configDaemonNodeSelector:
    node.kubernetes.io/location: edge
  featureGates:
    metricsExporter: true
