gitea:
    gitea:
        admin:
            password: ENC[AES256_GCM,data:vWheaFmBHoM=,iv:TNamIo5V4NljhOngMUl//5AgaGUP9T45cBBScsfzrJw=,tag:3iaI86W5b9w69vYqLoEduA==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUWlWK3E5QjBtTHV3b1R6
            eVJ0bVlNcHduWHUvT2FiUng4bCtTNW9HRlJRCkt1MjU3TFFzVFVjU1grWC9jbExN
            NmpnM0pRYkhPd3RzTmRmeTlGMkU4OVEKLS0tIHlhL2FYMWJGdUlYdkZSK1MvaDl2
            aDhtRlFjL3dub1JmVDNMNzhsWjBPN0kKLGRQbXnCjoksydOlNeX4ODvs1ggWtFRP
            rM7h3deUKpjGjzYLkm59tUh0v572Sxjcp76YpTotl9aALgAi5BGa3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T18:11:08Z"
    mac: ENC[AES256_GCM,data:Whuw0HF1qRNFuC0zKRH4xXE0E0iInHEfhTBPbLjEv+ORkAGm7qacTuDgnqV0DSV6gnlht2bWgp3d97YWTs8gfK9FDOq8vKTzuwaO3/bXSekZ1KSkemFjrFnO0CRHrENWA0CNOi4yUHeVaxpx6eL0QRJr7G+ewH9jWdTEKrAGN5A=,iv:tGxEjFGB5y6uHeH+G2ds6Jfw1wl8o9VYi65GTUKabGY=,tag:ht8MuaIfB1c39RO4u/3zgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
