gitea:
    gitea:
        admin:
            password: ENC[AES256_GCM,data:LOIFmeUbCCI=,iv:/GEJbMbYRKP86fOUjzX0h9cp8N7yFw1tXVMxj8hBrVs=,tag:5SzO8NOdWVmwWDQJ3nnlfA==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVXRDKzZBR3ZaZ3EwRUNX
            dGZ3Rng3RUY5V3BDWFQyZUpYQWtqcThLbFhRClR0WWFkLzZMUWFjTU5YbE1pMUtm
            eSt5V0pIQ0RuRGV1aXQ2V0xwV20wQ0UKLS0tIGEydXBHeStoVkVBTlZ1UTRLOGVt
            NVJVZTZiSG9lNXZsUk8xRityNWdReVEKDnqMX/j7lq3qLSRUxqNMq84NDYi1NQDL
            dpEhcCUxJeZFEOlMimQ6tGGy36AoI+ah1aaymwc2IeQYyydhyhasrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T16:06:42Z"
    mac: ENC[AES256_GCM,data:0c2EYGCTROCQh4BlzdSalI4zjD9BOmKiOEzLvxmcijwVW4pZM9qlWn4GTqAx1Aehgl0Jw2I+jZOteoo021zaprwhgaVXgsnfX6fa2HnN/71JRrE0bXezRanXVWKFHBmdpFkmWC/6/nqYJ0nFITOwGyYWBs44D+qMszmXAWUwW3g=,iv:kFGyTiIQ5wgIGcAkR24y7oXtgWwl0KMAwAshEg3Ufjw=,tag:q64dO36bm5d951gX5w+mkg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
