tailscale-operator:
    oauth:
        clientId: ENC[AES256_GCM,data:i53Ukfmjb6qd+r6zcxtesLs=,iv:7+Qc9hJjxqBDWg15JANvDeNZczH/6NSPdszm7hAt6PY=,tag:J3DxW3nc91AqhUNrzuiI0Q==,type:str]
        clientSecret: ENC[AES256_GCM,data:NV3r+aHzY0UQybOrQSfEUb4WdIvKNaxQWCveHUYKzNfQlBKruWWM7y8orlmDD9ZqD2TJvN9ugR2PopedxwSjhw==,iv:iEaNK/waPBfkxrnr0PDgLl7gOq7NwXGM928nwMa9SN8=,tag:0nuWRFAoYZk9QoSbOY5gfA==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOEdqUE5SUzlrWTFoZjJu
            bkJ5YWMremdWODBDcXlwR2gyYmFQYStZYlJBCnhETC8yM25jamVYTkJ5bkkrTmFJ
            ZExtVTY0NmZQYlJTbGxieTFtWHBWUVUKLS0tIFh4ZWZ4Yy9YbG1Db3BTMGNBaWgx
            OFcyK05oSTlIQ2ZZNWVwOXhyVE9HakkKe1bOazjVR0xREKcowQMr0qfbiU4dJjaP
            ydNlUjRhdhfcXgzkMDHgspNLN7melFnPgY1xCdIS3bIJvvLWxYOSJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T18:11:12Z"
    mac: ENC[AES256_GCM,data:Sx5EGRjzoN4F9Gf1emw3eMBuUEYDhOWTX6Ey685PCYRmqyLYSNV177Eg2VeT1aaDmZf2qECt3C2JS6R/CZsfPnI8ENCZvVzTpbO7+GUjPjjh/Dn43oSbOMAupL5k0yI6cZ6vYSz0v5DXOzUqh8nxbj32CrpLzM2qECwbKTq729Q=,iv:13Zdw+4zcdy90QBqpp6k0JTy/yCs0TiXPTp7MfBedKU=,tag:v6XPtBdtRQOPB17g/ET/Uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
