tailscale-operator:
    oauth:
        clientId: ENC[AES256_GCM,data:1WTzP9NWcrxsjDwro/InH0Y=,iv:+P0wnPdD1RNIwqWjrBzhfPzQQL8gmJMEAF/3akyYmlI=,tag:4TgN1qefqfIMF4gvNS9iUQ==,type:str]
        clientSecret: ENC[AES256_GCM,data:2lEddDDRriUx8c0w0MKJQRWBeyMqMQKAVairQcN4DL/tQXfHnLyZbI1NLh2WycsKAbeq+c7jnig8LbEZp+BsyQ==,iv:+EW6+2KHsNUoUyKyV0tTNpm9x/2zDO/X5daLcIFdvO0=,tag:G4zCTx59HxVnI062OIn+dA==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTDA0UUkrb1pDa1J2aUY5
            OHlCb2ZoeHdRNUkyTU0zQTVaVkwrWHE2b2xFCkY4QTR6L0NXdSs0NVBDQi9ocXlP
            K1hYeFRURHFZSytsc1ZMVktnWHFna2MKLS0tIElkK3lZeStvd0ZrQ2czSFpQZUVJ
            SnNSTElZeWxmdjQ3SEdjaXg5ckYzRlEKI+FjXUp+mjdmiHu6Iu1ofksa8xaDb35R
            ZK1nk1HUgtSVPsFY2InkO1iXFQtJD8B+B+G1ZUIxrtNmrdWvmcjpUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T12:31:53Z"
    mac: ENC[AES256_GCM,data:4/46QD8Pd5wQmwxikTqxrfO8PgBHpGLEP8qQvnwnVDVWawVESjn+SjnFfhrzn6eqH28un3H6Iit9Bn/pgY+nSsPsFH5ReVImLYZlGIR6CKcwJin2ijmBAoO0lKazdjojFXKLliGDIDB5luM0Nw/ghNwp6rBhMxF/ffrem9UlRwo=,iv:6bKfwxj+s8w5mHFx7gapRFbun/gALpq5xrz6wqXm4Pw=,tag:7r/oncyyi2Fc/AkBy9O4yg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
