tailscale-operator:
    oauth:
        clientId: ENC[AES256_GCM,data:T4gCxokrPktatbD4Hv1rBY4=,iv:GoRVy+Vo83HYjP6YWfL9wPWj1MTKz0OTSnBWrsmkAY4=,tag:EKB479tqZiIu8s9uosuRUA==,type:str]
        clientSecret: ENC[AES256_GCM,data:RftslkkzY80zlALfXloHNNSeGzkQEwnvUXARpHF+NCAgzqqPyvY+KXtJ42Q0pF1J/HTR1f9EoBvjZOLi1ypUZw==,iv:NDPurAXsRL1O3Jj7mQFZI2r2v0Pr9QPk0Xj+l/sedy8=,tag:7d130DXJ+JAQv+i0GRUHCw==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbFg2d3kzd3UwU1RZYmtt
            WTB6Rks4TWJNcE5vYUdzcitkN1FEZG16TjJJCnlkUEJQL2ZlTkFGQ2RDSUlHZy9K
            Z3lPV0hNN0hBZ1VKZ3ZLWDVRRE10QUUKLS0tIGdqNHBZVEEyMXRpU0ZXMkdteGxu
            RHh6NGhZWjNVVk41TUFIZjIzRXpjYTAKcukvj4J+rZwCbpCzfHplT+FP1bmtTMkt
            4B0evQu5dzFYElGUOA/1oTpdkSS0M3+awCzD3PVU0iNe759uZffibA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T16:06:53Z"
    mac: ENC[AES256_GCM,data:rfDKGbrQL9ZB9XL2ririjSCYQauOP61Kz7yEOjCgLG2OCb76TU+A6FcPdyiRu0cjY1vxi4Fv3mINjBPK8Y1eMMmS2cnfSLA8Kkt3fR2YZQI96HxrzC5oF6XX0N8gd9Ga3ro7zgPegqLH3oJQQ8ShiJv8Sxijv579q2XXgJHf7aI=,iv:P/HeRa9pUpUn1kMxlIrZxiUeEE0tiVTNeGTCmyu7c10=,tag:MMohDnBvWsgt/+DPrq6Scw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
